<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4783KNG" failures="0" tests="8" name="Default test" time="128.857" errors="0" timestamp="2023-05-18T15:48:53 EET">
  <testcase classname="Almosafer" name="@AfterTest myAfterTest" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	the default lang is arabic expected [English] but found [العربية]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
the default lang is arabic expected [English] but found [العربية]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Almosafer.myAfterTest(Almosafer.java:127)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterTest myAfterTest -->
  <testcase classname="Almosafer" name="check_the_website_default_currency" time="0.042"/>
  <testcase classname="Almosafer" name="check_contact_numbers" time="0.027"/>
  <testcase classname="Almosafer" name="check_the_Qitaf_logo" time="0.038"/>
  <testcase classname="Almosafer" name="hotels_search_tab" time="0.027"/>
  <testcase classname="Almosafer" name="Random_lang_selected" time="5.149"/>
  <testcase classname="Almosafer" name="hotel_search_tab" time="0.453"/>
  <testcase classname="Almosafer" name="Room_specifications" time="36.305"/>
  <testcase classname="Almosafer" name="check_the_website_default_language" time="1.757"/>
</testsuite> <!-- Default test -->
